version: '3.8'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: sakila
    ports:
      - "3306:3306"
    volumes:
      - sakila_data:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    networks:
      - sakila-network

volumes:
  sakila_data:

networks:
  sakila-network:
    driver: bridge